/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLauncher: typeof import('./src/components/AppLauncher.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    Canvas: typeof import('./src/components/builder/Canvas.vue')['default']
    DevPanel: typeof import('./src/components/builder/DevPanel.vue')['default']
    FieldPalette: typeof import('./src/components/builder/FieldPalette.vue')['default']
    FieldTypePicker: typeof import('./src/components/builder/FieldTypePicker.vue')['default']
    FormSettingsDialog: typeof import('./src/components/builder/FormSettingsDialog.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Inspector: typeof import('./src/components/builder/Inspector.vue')['default']
    PageNav: typeof import('./src/components/public/PageNav.vue')['default']
    ProgressBar: typeof import('./src/components/public/ProgressBar.vue')['default']
    RespondentField: typeof import('./src/components/RespondentField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./src/components/ShareDialog.vue')['default']
    SignaturePad: typeof import('./src/components/SignaturePad.vue')['default']
    SubmissionsList: typeof import('./src/components/public/SubmissionsList.vue')['default']
    SuccessScreen: typeof import('./src/components/public/SuccessScreen.vue')['default']
  }
}
