import frappeUIPreset from 'frappe-ui/tailwind'

export default {
  presets: [frappeUIPreset],
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/frappe-ui/src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  // The <Icon> wrapper renders frappe-ui's lucide-* mask classes dynamically
  // (`lucide-${name}`), so Tailwind's JIT never sees them as literals. Safelist
  // every icon name the app passes to <Icon> (and to frappe-ui icon props) so
  // their CSS is always generated. Keep in sync when adding a new icon.
  safelist: [
    'lucide-archive',
    'lucide-archive-restore',
    'lucide-arrow-right',
    'lucide-asterisk',
    'lucide-at-sign',
    'lucide-award',
    'lucide-bar-chart-2',
    'lucide-bell',
    'lucide-calendar',
    'lucide-calendar-clock',
    'lucide-chart-no-axes-column',
    'lucide-check',
    'lucide-check-check',
    'lucide-chevron-down',
    'lucide-chevron-right',
    'lucide-circle',
    'lucide-circle-alert',
    'lucide-circle-dot',
    'lucide-clipboard-list',
    'lucide-clock',
    'lucide-code-2',
    'lucide-copy',
    'lucide-corner-down-right',
    'lucide-database',
    'lucide-download',
    'lucide-edit-2',
    'lucide-ellipsis',
    'lucide-eye',
    'lucide-file-check-2',
    'lucide-file-question',
    'lucide-file-text',
    'lucide-git-branch',
    'lucide-git-merge',
    'lucide-globe',
    'lucide-grid',
    'lucide-grid-3x3',
    'lucide-grip-vertical',
    'lucide-hard-drive',
    'lucide-hash',
    'lucide-heading',
    'lucide-image',
    'lucide-inbox',
    'lucide-info',
    'lucide-layout-grid',
    'lucide-layout-template',
    'lucide-link',
    'lucide-list',
    'lucide-list-checks',
    'lucide-loader',
    'lucide-lock',
    'lucide-lock-open',
    'lucide-log-out',
    'lucide-mail',
    'lucide-map-pin',
    'lucide-messages-square',
    'lucide-minus',
    'lucide-paperclip',
    'lucide-pen-line',
    'lucide-pencil',
    'lucide-phone',
    'lucide-plus',
    'lucide-plus-circle',
    'lucide-presentation',
    'lucide-rocket',
    'lucide-search',
    'lucide-settings',
    'lucide-share-2',
    'lucide-shield',
    'lucide-shield-check',
    'lucide-sliders-horizontal',
    'lucide-sparkles',
    'lucide-star',
    'lucide-table',
    'lucide-table-2',
    'lucide-toggle-left',
    'lucide-trash-2',
    'lucide-type',
    'lucide-user-check',
    'lucide-user-plus',
    'lucide-users',
    'lucide-video',
    'lucide-x',
  ],
}
